### ISSUE TITLE
player:hud glitches

### ISSUE THREAD

**Issue by SwissalpS** [SwissalpS/postool#6]
I just got hit real bad by the bug: fullscreen is coloured and error messages: "can't load texture" and the text of the huds. Somehow the hud manager mistakes text huds as image huds.

To avoid, let's try by creating the hud elements when user activates and destroy them on deactivation.
That should reset the elements at least.

**Comment by SwissalpS** [comment]
hmm, that theory may not work. I logged out which should invoke removal and recreation on login, but I had the effects even after relog.

Edit: logging in as other player, I have no trouble, only have trouble with one player.

**Comment by SwissalpS** [comment]
https://github.com/SwissalpS/postool/tree/healing
this works on my singleplayer setup. Would like some feedback from testers before I merge into master.
It now re-creates the hud elements on toggle, giving hud-engine a chance to 'heal'.

**Comment by 6r1d** [comment]
> To avoid, let's try by creating the hud elements when user activates and destroy them on deactivation.

I checked out "healing" branch, but it is updating by itself with activated hud.
Should it work this way or I tested something else?

> "can't load texture" and the text of the huds. Somehow the hud manager mistakes text huds as image huds.

By the way, do you have a screenshot with a texture name?
It'd be interesting to know which image it is trying to load.
Or is it just HUD info as an image name?

**Comment by SwissalpS** [comment]
it seems to mistake 'text' hud elements for 'image' elements and tries to load a texture with name of what the text to display should be.

What do you mean "It is activating by itself" ? Things to test: do the items stack properly when enabling disabling them, how does it work on different screen sizes.

**Comment by SwissalpS** [comment]
> I checked out "healing" branch, but it is updating by itself with activated hud.
the tool makes a grid show for x seconds. The HUD updates itself every 2 seconds by default.
Interesting idea though, to have the HUD hold value of last tool use. Essentially that is what missions wands do, save a position.

**Comment by SwissalpS** [comment]
v0.2 should at least give users a way to fix the HUD-glitch
