### ISSUE TITLE
as long as on_leaveplayer() does not get exectuted, there will be issues

### ISSUE THREAD

**Issue by SwissalpS** [SwissalpS/postool#7]
https://github.com/SwissalpS/postool/blob/955e08f29ee9ec2655ef3a04bd17b0ec69db8e0c/init.lua#L48
Seems on_leaveplayer() does not always get exectuted or we would have seen the bug in testing.

**Comment by thomasrudin** [comment]
This does not work: the `player` object can't be reliably persisted across server-steps, it should work the the name (`player:get_player_name()`) though...

For example the `name` variable here: https://github.com/D00Med/scifi_nodes/blob/master/palm_scanner.lua#L24

**PS**: about the recent crash: i haven't reviewed the server-logs yet

**Comment by SwissalpS** [comment]
Thanks, I'll change that.

**Comment by SwissalpS** [comment]
made a branch with the changes, ready for testing
https://github.com/SwissalpS/postool/tree/namefix0

**Comment by SwissalpS** [comment]
https://github.com/SwissalpS/postool/commit/b24faec74eac5a1280535bfb4a406667e59bf797
fixes and closes the issue.

@coil0 @thomasrudin @6r1d I rebuilt the server from source and was able to recreate the crashes. Am going to add a way to reset to server defaults for the few of us who got their data corrupted.

**Comment by thomasrudin** [comment]
Why did you need to build the server from source? Was it an engine-issue?

**By the way**: i couldn't retrieve the logs, it already rolled over it :/

**Comment by SwissalpS** [comment]
np about the logs, I was able to recreate and solve the issue.

My previous build didn't react to the errors at all, no crash no message. Not use-able test-environment.
So I built from source to be sure :)
